export const ratioTable = [
  {
    id: 0,
    ratio: "3/2",
    cents: 701.955,
    intervalName: "Perfect Fifth",
    invertedRatio: "4/3",
    invertedCents: 498.045,
    invertedName: "Perfect Fourth",
    prime: true,
    primeLimit: 3,
    harmonics: true,
    majorDiatonic: true,
    harmonicSix: true,
  },
  {
    id: 1,
    ratio: "5/4",
    cents: 386.31371,
    intervalName: "Major 3rd",
    invertedRatio: "8/5",
    invertedCents: 813.68628,
    invertedName: "Minor Sixth",
    prime: true,
    primeLimit: 5,
    harmonics: true,
    majorDiatonic: true,
    harmonicSix: true,
  },
  {
    id: 2,
    ratio: "5/3",
    cents: 884.35871,
    intervalName: "Major Sixth",
    invertedRatio: "6/5",
    invertedCents: 315.641287,
    invertedName: "Minor Third",
    prime: false,
    primeLimit: 5,
    harmonics: true,
    majorDiatonic: true,
    harmonicSix: true,
  },
  {
    id: 3,
    ratio: "7/6",
    cents: 266.8709,
    intervalName: "Septimal Minor Third",
    invertedRatio: "12/7",
    invertedCents: 933.12909,
    invertedName: "Septimal Major Sixth",
    prime: true,
    primeLimit: 7,
    harmonics: true,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 4,
    ratio: "7/5",
    cents: 582.51219,
    intervalName: "Septimal Tritone",
    invertedRatio: "10/7",
    invertedCents: 617.4878,
    invertedName: "Euler's Tritone",
    prime: false,
    primeLimit: 7,
    harmonics: false,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 5,
    ratio: "7/4",
    cents: 968.8259,
    intervalName: "Harmonic Seventh",
    invertedRatio: "8/7",
    invertedCents: 231.17409,
    invertedName: "Septimal Whole Tone",
    prime: false,
    primeLimit: 7,
    harmonics: true,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 6,
    ratio: "9/8",
    cents: 203.91,
    intervalName: "Major Second",
    invertedRatio: "16/8",
    invertedCents: 996.08999,
    invertedName: "Minor Seventh",
    prime: false,
    primeLimit: 3,
    harmonics: true,
    majorDiatonic: true,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 7,
    ratio: "9/7",
    cents: 435.08409,
    intervalName: "Septimal Major Third",
    invertedRatio: "14/9",
    invertedCents: 764.9159,
    invertedName: "Septimal Minor Sixth",
    prime: false,
    primeLimit: 7,
    harmonics: false,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 8,
    ratio: "9/5",
    cents: 1017.596288,
    intervalName: "Just Minor Seventh",
    invertedRatio: "10/9",
    invertedCents: 182.403712,
    invertedName: "Just Major Sixth",
    prime: false,
    primeLimit: 5,
    harmonics: true,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 9,
    ratio: "11/10",
    cents: 165.00422,
    intervalName: "Ptolemy's Second",
    invertedRatio: "20/11",
    invertedCents: 1034.99577,
    invertedName: "Large Minor Seventh",
    prime: true,
    primeLimit: 11,
    harmonics: true,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 10,
    ratio: "11/9",
    cents: 347.40794,
    intervalName: "Undecimal Neutral Third",
    invertedRatio: "18/11",
    invertedCents: 852.59205,
    invertedName: "Undecimal Neutral Sixth",
    prime: false,
    primeLimit: 11,
    harmonics: false,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 11,
    ratio: "11/8",
    cents: 551.31794,
    intervalName: "Undecimal Semi-Augmented Fourth",
    invertedRatio: "16/11",
    invertedCents: 648.68205,
    invertedName: "Undecimal Semi-Diminished Fifth",
    prime: false,
    primeLimit: 11,
    harmonics: false,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 12,
    ratio: "11/7",
    cents: 782.49203,
    intervalName: "Undecimal Augmented Fifth",
    invertedRatio: "14/11",
    invertedCents: 417.50796,
    invertedName: "Undecimal Diminished Fourth",
    prime: false,
    primeLimit: 11,
    harmonics: false,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 13,
    ratio: "11/6",
    cents: 1049.36294,
    intervalName: "Undecimal Neutral Seventh",
    invertedRatio: "12/11",
    invertedCents: 150.63705,
    invertedName: "Undecimal Neutral Second",
    prime: false,
    primeLimit: 11,
    harmonics: true,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 14,
    ratio: "13/12",
    cents: 138.57266,
    intervalName: "Tridecimal  2/3rds Tone",
    invertedRatio: "24/13",
    invertedCents: 1061.42733,
    invertedName: "Tridecimal Neutral Seventh",
    prime: true,
    primeLimit: 13,
    harmonics: true,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 15,
    ratio: "13/11",
    cents: 289.20971,
    intervalName: "Tridecimal Minor Third",
    invertedRatio: "22/13",
    invertedCents: 910.79028,
    invertedName: "Tridecimal Major Sixth",
    prime: false,
    primeLimit: 13,
    harmonics: false,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 16,
    ratio: "13/10",
    cents: 454.21394,
    intervalName: "Tridecimal Semi-Diminished Fifth",
    invertedRatio: "20/13",
    invertedCents: 745.78605,
    invertedName: "Tridecimal Semi-Augmented Fifth",
    prime: false,
    primeLimit: 13,
    harmonics: false,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 17,
    ratio: "13/9",
    cents: 636.61766,
    intervalName: "Tridecimal Diminished Fifth",
    invertedRatio: "18/13",
    invertedCents: 563.38234,
    invertedName: "Tridecimal Augmented Fourth",
    prime: false,
    primeLimit: 13,
    harmonics: false,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 18,
    ratio: "13/8",
    cents: 840.52766,
    intervalName: "Tridecimal Neutral Sixth",
    invertedRatio: "16/13",
    invertedCents: 359.472338,
    invertedName: "Tridecimal Neutral Third",
    prime: false,
    primeLimit: 13,
    harmonics: false,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 19,
    ratio: "13/7",
    cents: 1071.70175,
    intervalName: "16/3rds Tone",
    invertedRatio: "14/13",
    invertedCents: 128.29824,
    invertedName: "2/3rds Tone",
    prime: false,
    primeLimit: 13,
    harmonics: true,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 20,
    ratio: "15/14",
    cents: 119.4428,
    intervalName: "Major Diatonic Semitone",
    invertedRatio: "28/15",
    invertedCents: 1080.55719,
    invertedName: "Grave Major Seventh",
    prime: false,
    primeLimit: 7,
    harmonics: true,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 21,
    ratio: "15/13",
    cents: 247.74105,
    intervalName: "Tridecimal 5/4ths Tone",
    invertedRatio: "26/15",
    invertedCents: 952.25894,
    invertedName: "Tridecimal Semi-Augmented Sixth",
    prime: false,
    primeLimit: 13,
    harmonics: false,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 22,
    ratio: "15/11",
    cents: 536.95077,
    intervalName: "Undecimal Augmented Fourth",
    invertedRatio: "22/15",
    invertedCents: 663.04922,
    invertedName: "Undecimal Diminished Fifth",
    prime: false,
    primeLimit: 11,
    harmonics: false,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 23,
    ratio: "15/8",
    cents: 1088.26871,
    intervalName: "Classic Major Seventh",
    invertedRatio: "16/15",
    invertedCents: 111.73128,
    invertedName: "Minor Diatonic Semitone",
    prime: false,
    primeLimit: 5,
    harmonics: true,
    majorDiatonic: true,
    harmonicSix: false,
  },
  {
    id: 24,
    ratio: "17/16",
    cents: 104.95541,
    intervalName: "Seventeenth Harmonic",
    invertedRatio: "32/17",
    invertedCents: 104.95541,
    invertedName: "Seventeenth Subharmonic",
    prime: true,
    primeLimit: 17,
    harmonics: true,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 25,
    ratio: "17/15",
    cents: 216.68669,
    intervalName: "Septendecimal Major Second",
    invertedRatio: "30/17",
    invertedCents: 983.3133,
    invertedName: "Septendecimal Minor Seventh",
    prime: false,
    primeLimit: 17,
    harmonics: false,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 26,
    ratio: "17/14",
    cents: 336.1295,
    intervalName: "Supraminor Third",
    invertedRatio: "28/17",
    invertedCents: 863.87049,
    invertedName: "Submajor Sixth",
    prime: false,
    primeLimit: 17,
    harmonics: false,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 27,
    ratio: "17/13",
    cents: 464.42774,
    intervalName: "17/13",
    invertedRatio: "26/17",
    invertedCents: 735.57225,
    invertedName: "26/17",
    prime: false,
    primeLimit: 17,
    harmonics: false,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 28,
    ratio: "17/12",
    cents: 603.000409,
    intervalName: "Second Septendecimal Tritone",
    invertedRatio: "24/17",
    invertedCents: 596.999591,
    invertedName: "First Septendecimal Tritone",
    prime: false,
    primeLimit: 17,
    harmonics: false,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 29,
    ratio: "17/11",
    cents: 753.637467,
    intervalName: "17/11",
    invertedRatio: "22/17",
    invertedCents: 446.362533,
    invertedName: "22/17",
    prime: false,
    primeLimit: 17,
    harmonics: false,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 30,
    ratio: "17/10",
    cents: 918.64169,
    intervalName: "Septendecimal Diminished Seventh",
    invertedRatio: "20/17",
    invertedCents: 281.3583,
    invertedName: "Septendecimal Augmented Second",
    prime: false,
    primeLimit: 17,
    harmonics: false,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 31,
    ratio: "17/9",
    cents: 1101.0454,
    intervalName: "Septendecimal Major Seventh",
    invertedRatio: "18/17",
    invertedCents: 98.95459,
    invertedName: "Septendecimal Minor Second",
    prime: false,
    primeLimit: 17,
    harmonics: true,
    majorDiatonic: false,
    harmonicSix: false,
  },
];
