import getCentsFromRatio from "./util/getCentsFromRatio";

export const ratioTable = [
  {
    id: 0,
    ratio: "3/2",
    cents: getCentsFromRatio(3, 2),
    intervalName: "Perfect Fifth",
    invertedRatio: "4/3",
    invertedCents: getCentsFromRatio(4, 3),
    invertedName: "Perfect Fourth",
    prime: true,
    primeLimit: 3,
    harmonics: true,
    majorDiatonic: true,
    harmonicSix: true,
  },
  {
    id: 1,
    ratio: "5/4",
    cents: getCentsFromRatio(5, 4),
    intervalName: "Major 3rd",
    invertedRatio: "8/5",
    invertedCents: getCentsFromRatio(8, 5),
    invertedName: "Minor Sixth",
    prime: true,
    primeLimit: 5,
    harmonics: true,
    majorDiatonic: true,
    harmonicSix: true,
  },
  {
    id: 2,
    ratio: "5/3",
    cents: 884.35871,
    intervalName: getCentsFromRatio(5, 3),
    invertedRatio: "6/5",
    invertedCents: 315.641287,
    invertedName: getCentsFromRatio(6, 5),
    prime: false,
    primeLimit: 5,
    harmonics: true,
    majorDiatonic: true,
    harmonicSix: true,
  },
  {
    id: 3,
    ratio: "7/6",
    cents: getCentsFromRatio(7, 6),
    intervalName: "Septimal Minor Third",
    invertedRatio: "12/7",
    invertedCents: getCentsFromRatio(12, 7),
    invertedName: "Septimal Major Sixth",
    prime: true,
    primeLimit: 7,
    harmonics: true,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 4,
    ratio: "7/5",
    cents: getCentsFromRatio(7, 5),
    intervalName: "Septimal Tritone",
    invertedRatio: "10/7",
    invertedCents: getCentsFromRatio(10, 7),
    invertedName: "Euler's Tritone",
    prime: false,
    primeLimit: 7,
    harmonics: false,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 5,
    ratio: "7/4",
    cents: getCentsFromRatio(7, 4),
    intervalName: "Harmonic Seventh",
    invertedRatio: "8/7",
    invertedCents: getCentsFromRatio(8, 7),
    invertedName: "Septimal Whole Tone",
    prime: false,
    primeLimit: 7,
    harmonics: true,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 6,
    ratio: "9/8",
    cents: getCentsFromRatio(9, 8),
    intervalName: "Major Second",
    invertedRatio: "16/9",
    invertedCents: getCentsFromRatio(16, 9),
    invertedName: "Minor Seventh",
    prime: false,
    primeLimit: 3,
    harmonics: true,
    majorDiatonic: true,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 7,
    ratio: "9/7",
    cents: getCentsFromRatio(9, 7),
    intervalName: "Septimal Major Third",
    invertedRatio: "14/9",
    invertedCents: getCentsFromRatio(14, 9),
    invertedName: "Septimal Minor Sixth",
    prime: false,
    primeLimit: 7,
    harmonics: false,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 8,
    ratio: "9/5",
    cents: getCentsFromRatio(9, 5),
    intervalName: "Just Minor Seventh",
    invertedRatio: "10/9",
    invertedCents: getCentsFromRatio(10, 9),
    invertedName: "Just Major Sixth",
    prime: false,
    primeLimit: 5,
    harmonics: true,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 9,
    ratio: "11/10",
    cents: getCentsFromRatio(11, 10),
    intervalName: "Ptolemy's Second",
    invertedRatio: "20/11",
    invertedCents: getCentsFromRatio(20, 11),
    invertedName: "Large Minor Seventh",
    prime: true,
    primeLimit: 11,
    harmonics: true,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 10,
    ratio: "11/9",
    cents: getCentsFromRatio(11, 9),
    intervalName: "Undecimal Neutral Third",
    invertedRatio: "18/11",
    invertedCents: getCentsFromRatio(18, 11),
    invertedName: "Undecimal Neutral Sixth",
    prime: false,
    primeLimit: 11,
    harmonics: false,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 11,
    ratio: "11/8",
    cents: getCentsFromRatio(11, 8),
    intervalName: "Undecimal Semi-Augmented Fourth",
    invertedRatio: "16/11",
    invertedCents: getCentsFromRatio(16, 11),
    invertedName: "Undecimal Semi-Diminished Fifth",
    prime: false,
    primeLimit: 11,
    harmonics: false,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 12,
    ratio: "11/7",
    cents: getCentsFromRatio(11, 7),
    intervalName: "Undecimal Augmented Fifth",
    invertedRatio: "14/11",
    invertedCents: getCentsFromRatio(14, 11),
    invertedName: "Undecimal Diminished Fourth",
    prime: false,
    primeLimit: 11,
    harmonics: false,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 13,
    ratio: "11/6",
    cents: getCentsFromRatio(11, 6),
    intervalName: "Undecimal Neutral Seventh",
    invertedRatio: "12/11",
    invertedCents: getCentsFromRatio(12, 11),
    invertedName: "Undecimal Neutral Second",
    prime: false,
    primeLimit: 11,
    harmonics: true,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 14,
    ratio: "13/12",
    cents: getCentsFromRatio(13, 12),
    intervalName: "Tridecimal  2/3rds Tone",
    invertedRatio: "24/13",
    invertedCents: getCentsFromRatio(24, 13),
    invertedName: "Tridecimal Neutral Seventh",
    prime: true,
    primeLimit: 13,
    harmonics: true,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 15,
    ratio: "13/11",
    cents: getCentsFromRatio(13, 11),
    intervalName: "Tridecimal Minor Third",
    invertedRatio: "22/13",
    invertedCents: getCentsFromRatio(22, 13),
    invertedName: "Tridecimal Major Sixth",
    prime: false,
    primeLimit: 13,
    harmonics: false,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 16,
    ratio: "13/10",
    cents: getCentsFromRatio(13, 10),
    intervalName: "Tridecimal Semi-Diminished Fifth",
    invertedRatio: "20/13",
    invertedCents: getCentsFromRatio(20, 13),
    invertedName: "Tridecimal Semi-Augmented Fifth",
    prime: false,
    primeLimit: 13,
    harmonics: false,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 17,
    ratio: "13/9",
    cents: getCentsFromRatio(13, 9),
    intervalName: "Tridecimal Diminished Fifth",
    invertedRatio: "18/13",
    invertedCents: getCentsFromRatio(18, 13),
    invertedName: "Tridecimal Augmented Fourth",
    prime: false,
    primeLimit: 13,
    harmonics: false,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 18,
    ratio: "13/8",
    cents: getCentsFromRatio(13, 8),
    intervalName: "Tridecimal Neutral Sixth",
    invertedRatio: "16/13",
    invertedCents: getCentsFromRatio(16, 13),
    invertedName: "Tridecimal Neutral Third",
    prime: false,
    primeLimit: 13,
    harmonics: false,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 19,
    ratio: "13/7",
    cents: getCentsFromRatio(13, 7),
    intervalName: "16/3rds Tone",
    invertedRatio: "14/13",
    invertedCents: getCentsFromRatio(14, 13),
    invertedName: "2/3rds Tone",
    prime: false,
    primeLimit: 13,
    harmonics: true,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 20,
    ratio: "15/14",
    cents: getCentsFromRatio(15, 14),
    intervalName: "Major Diatonic Semitone",
    invertedRatio: "28/15",
    invertedCents: getCentsFromRatio(28, 15),
    invertedName: "Grave Major Seventh",
    prime: false,
    primeLimit: 7,
    harmonics: true,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 21,
    ratio: "15/13",
    cents: getCentsFromRatio(15, 13),
    intervalName: "Tridecimal 5/4ths Tone",
    invertedRatio: "26/15",
    invertedCents: getCentsFromRatio(26, 15),
    invertedName: "Tridecimal Semi-Augmented Sixth",
    prime: false,
    primeLimit: 13,
    harmonics: false,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 22,
    ratio: "15/11",
    cents: getCentsFromRatio(15, 11),
    intervalName: "Undecimal Augmented Fourth",
    invertedRatio: "22/15",
    invertedCents: getCentsFromRatio(22, 15),
    invertedName: "Undecimal Diminished Fifth",
    prime: false,
    primeLimit: 11,
    harmonics: false,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 23,
    ratio: "15/8",
    cents: getCentsFromRatio(15, 8),
    intervalName: "Classic Major Seventh",
    invertedRatio: "16/15",
    invertedCents: getCentsFromRatio(16, 15),
    invertedName: "Minor Diatonic Semitone",
    prime: false,
    primeLimit: 5,
    harmonics: true,
    majorDiatonic: true,
    harmonicSix: false,
  },
  {
    id: 24,
    ratio: "17/16",
    cents: getCentsFromRatio(17, 16),
    intervalName: "Seventeenth Harmonic",
    invertedRatio: "32/17",
    invertedCents: getCentsFromRatio(32, 17),
    invertedName: "Seventeenth Subharmonic",
    prime: true,
    primeLimit: 17,
    harmonics: true,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 25,
    ratio: "17/15",
    cents: getCentsFromRatio(17, 15),
    intervalName: "Septendecimal Major Second",
    invertedRatio: "30/17",
    invertedCents: getCentsFromRatio(30, 17),
    invertedName: "Septendecimal Minor Seventh",
    prime: false,
    primeLimit: 17,
    harmonics: false,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 26,
    ratio: "17/14",
    cents: getCentsFromRatio(17, 14),
    intervalName: "Supraminor Third",
    invertedRatio: "28/17",
    invertedCents: getCentsFromRatio(28, 17),
    invertedName: "Submajor Sixth",
    prime: false,
    primeLimit: 17,
    harmonics: false,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 27,
    ratio: "17/13",
    cents: getCentsFromRatio(17, 13),
    intervalName: "17/13",
    invertedRatio: "26/17",
    invertedCents: getCentsFromRatio(26, 17),
    invertedName: "26/17",
    prime: false,
    primeLimit: 17,
    harmonics: false,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 28,
    ratio: "17/12",
    cents: getCentsFromRatio(17, 12),
    intervalName: "Second Septendecimal Tritone",
    invertedRatio: "24/17",
    invertedCents: getCentsFromRatio(24, 17),
    invertedName: "First Septendecimal Tritone",
    prime: false,
    primeLimit: 17,
    harmonics: false,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 29,
    ratio: "17/11",
    cents: getCentsFromRatio(17, 11),
    intervalName: "17/11",
    invertedRatio: "22/17",
    invertedCents: getCentsFromRatio(22, 17),
    invertedName: "22/17",
    prime: false,
    primeLimit: 17,
    harmonics: false,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 30,
    ratio: "17/10",
    cents: getCentsFromRatio(17, 10),
    intervalName: "Septendecimal Diminished Seventh",
    invertedRatio: "20/17",
    invertedCents: getCentsFromRatio(20, 17),
    invertedName: "Septendecimal Augmented Second",
    prime: false,
    primeLimit: 17,
    harmonics: false,
    majorDiatonic: false,
    harmonicSix: false,
  },
  {
    id: 31,
    ratio: "17/9",
    cents: getCentsFromRatio(17, 9),
    intervalName: "Septendecimal Major Seventh",
    invertedRatio: "18/17",
    invertedCents: getCentsFromRatio(18, 17),
    invertedName: "Septendecimal Minor Second",
    prime: false,
    primeLimit: 17,
    harmonics: true,
    majorDiatonic: false,
    harmonicSix: false,
  },
];
